name: nomadics
run-name: Setting the code for the DB
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: test output
      run: echo "This is my first test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: select version
      run: sudo apt-get update -y ; sudo apt-get install --yes --no-install-recommends postgresql-client
    - uses: actions/checkout@v4
    - name: test connection      
      run: psql -h${{ secrets.DBHOSTNAME }} -d${{ secrets.DB_NAME }} -U${{ secrets.DB_USER }} -W${{ secrets.DB_PASSWORD }} -c "select current_user"

