name: nomadics
run-name: Setting the code for the DB
on: [push]
jobs:
  test-output:
    runs-on: ubuntu-latest
    steps:
    - name: test output
      run: echo "This is my first test"
  connect-remote:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: show server_version();
      run: psql -h${{ secrets.DBHOSTNAME}} -d${{secrets.DB_NAME}} -U${{secrets.DB_USER}} -p${{secrets.DB_PASSWORD}} --port 5432 
